[[redirects]]
  from = "/info"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/tokens"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/tokens/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/claim/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/wallet"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/featured"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/airdrop"
  to = "/index.html"
  status = 20

[[redirects]]
  from = "/ssw-debug"
  to = "/index.html"
  status = 200

