[[redirects]]
  from = "/info"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/tokens"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/wallet"
  to = "/index.html"
  status = 200
